var captions = [

	'What a piece of junk!...food',
	'She\’s the ship that did the ketchup run in twelve patties',
	'Munch it, Chewie!',
	'What a piece of lunch!',
	'Do or do not, there is no fries.',
	'Indigestion is implied in our mandate.',
	'If you disappoint me again, I\'ll take bite of your ship so big, you won\'t be able to go near a civilised system for the rest of your life.',
	'We\‘re in a pickle now.',
	'But olive this ship all the same.',
	'I hope that\'s wholemeal or we\'re not going to get below like, twenty parsecs, Chewie',
	'Hokey Religions are nothing compared to fries on the side',
	'...And then she said that the cave was collapsing and so I said, \'This is no cave.\'',
	'So that\’s the Meal-ennium Full-tum?',
	'I would gladly pay you Tuesday for a ride to Alderaan today.',
	'Yeah, Chewie ordered it but he couldn’t finish it. His Mos Eisley were bigger than his Mos Stomachley.',
	'I know it doesn\'t look like much, but it\'s all we\'ve got for lunch.',
	'Okay, I agree ... some of the original effects look a little cheesy now.',
	'And I though Leia had big buns!',
	'You will never find a more wretched hive of bun and sesame.',
	'No, Artoo! I said ‘Let\’s do a cameo on Sesame Street’ not \‘Let\’s go to Kamino on Sesame Seeds!\’',
	'Going to Kamino “on sesame seeds” is truly the only way to fly, as Steve Obi-Wan Ben Larry Kenobi could tell us',
	'She\'s fast food enough for you, old man',
	'Two all beef patties, special sauce, lettuce, cheese, pickles, onions, made the Kessel run.',
	'You\’re gonna eat all that? You\’re braver than l thought.',
	'I\'ve outfed Imperial starchefs. Not the dollar menu mind you, I\'m talking about the extra value meals',
	'I don\'t know I can eat quite a lot',
	'Ugh I *hate* these special editions.',
	'I\'m confused. Did Disney buy McDonald\'s or The New Yorker?',
	'Uh. Deck Officer!!!',
	'Way too many calories in that thing.',
	'She’\s the fastest hunk of junk food in the galaxy',
	'Who\’s gonna fry it, kid, you?',
	'Ten thousand! We could have bought a whole meal for that!',
	'She may not look like lunch, but she’s got it where it counts, kid. I\’ve added some special condiments myself.',
	'Well you tell Wendy that Han Solo just stole it back!',
	'Han mostly uses it for smuggling carbos.',
	'Obi Wan: And you know what they call a... a... a Quarter Pounder with Cheese on Alderaan? Luke: They don\'t call it a Quarter Pounder with cheese?',
	'\"I call it the....\" \"Please don\'t.\" \"...Hanburger.\"',
	'Please, Hamburglar, don\'t hurt \'em.',
	'Do you want to supersize that 94 for 15,000 more?',
	'10,000? We could almost get a side of fries and a shake for that.',
	'Yeah, but who\’s gonna fry \‘em, kid? You?',
	'Alderaan? I thought you needed a ride to Flavortown.',
	'Well done.',
	'Ugh, too Chewie',
	'Fine, you can go solo.',
	'It may not cut the mustard, but it\’ll get you out of a pickle before other ships can ketchup. Let\’s roll!',
	'This is fast food. He said fast ship.',
	'She may not look like much bit she\'s delicious.',
	'It\'ll give you the Kessel runs in 12 parsecs.',
	'If we can pull this off, we\'ll eat like kings.',
	'If I hadn\’t learned to make sandwiches we would\’ve starved to death by now!',
	'Everything else aside, what\’s with that olive?',
	'The olive is aside, everything else is regular.',
	'The entire ship is one big burger.',
	'She may not look like much, but she\’s got it where it counts, kid. I\’ve made some special sauce modifications myself.',
	'Where\’s the beef?',
	'I got it the same place this Doctor friend of mine got his screwdriver ...',
	'Jabba, you\’re a wonderful human being.',
	'In that?',
	'Kid, I\'ve flown from one side of this galaxy to the other, I seen a lot of strange stuff, but I\'ve never seen ANYthing to make me believe there\'s one all powerful SAUCE that goes with EVERYthing.',
	'McDonald\'s acquisition of Disney',
	'Special Sauce Edition',
	'Olive you. I know.',
	'No no no! I said make it look LIKE my hamburger!',
	'Your focus determines your reality. Dammit Chewie!',
	'Is that an Angel?',
	'Chewy, it looks chewy...',
	'You know, if you think about it, a starship is a kind of sandwich.',
	'Looks like Porkins beat us to it.',
	'Fastest hunk a junk food in the galaxy.',
	'Mace Windu just can\'t resist a \"tasty burger\"',
	'Dad, Taun We is here.',
	'What the Christian hell is that?',
	'Now the slug has a taste for it.',
	'I haven\’t had a Jawa burger in a long time....long time.',
	'I’m starting to see why Jabba put a bounty on his head...',
	'94 calories',
	'Shotgun',
	'Chewie! That Kashyyyk Kush is NO JOKE!',
	'What a piece of junk...food!',
	'They say Jabba\'s in bed with one of those every night at 6:30.',
	'...made the Burger Run in less than twelve parsecs.',
	'If carbs is all you love then that’s what you’ll receive',
	'What a pile of chuck!',
	'What\'s a cow?',
	'It\'s a McQuarrie of McDonalds',
	'It may not look like much, but its got it where it counts.',
	'Han ate first!',
	'86 Docking Bay 94',
	'86 Order 66',
	'It\’s the ship that made the drive-thru run in 12 parsecs',
	'I\'ve added some special condiments myself...',
	'MUNCH IT CHEWIE!',
	'I will never visit the Imperial Museum of Contemporary Art again.',
	'Wipe them out. Olive them.',
	'It\'s true....olive it',
	'It\'s a sign from the force Luke, look for the Buns?',
	'This design origin story looks delicious but apocryphal.',
	'There\’s always a bigger fish filet',
	'I don\’t think the Empire had Wookiees in mind when they designed her, Chewie.',
	'How many hours on the Dykstraflex to work this off? Three. The answer is three.',
	'What\'s the cargo? Only toppings. Tomatoes, lettuce, an olive... and no questions.',
	'She\'ll make point five past bite speed.',
	'She\'ll make point five past \'bite me.\'',
	'But who\'s gonna eat it, kid? You?',
	'Dex\'s Diner: More than just Jawa Juice',
	'I thought you said the pilot was Ham Solo.',
	'No I said it was steamed Hans',
	'I swear. I left it RIGHT here.',
	'What about the droid attack on the Whoppers?',
	'Have it your way, kid',
	'It\'s the ship that made the inspectors run in less than 12 health checks.',
	'Well, looks like the concept designers have been working during lunch again.',
	'Oh dear, our odds at escaping on that are... *Threepio\'s head explodes',
	'Translated from shyriiwook: Noooo! You can tell from the meat that he stirred, whipped, then whipped again before going back to stirring! That burger\'s no good!',
	'She\'ll make point five past lunch time',
	'♫\”Cheeseburger and a pair of dice\”&#9835;',
	'What a piece of chuck',
	'Great, Chewie. Always thinking with your stomach.',
	'If this ship is as juicy as his boasting, we ought to do well',
	'She may look like lunch, but she\'s got it where it counts, kid',
	'Just myself, two all-beef beef patties, “special” sauce, lettuce, the boy, cheese, pickles, two droids, onions on a sesame seed bun...and no questions asked”',
	'is that for here or to go?',
	'Concept art from George Lucas\' lesser known sequel to American Graffiti',
	'I guess he wasn\’t boasting, they really did barely escape a giant space slug.',
	'The Empire will never ketchup to us in this little baby',
	'Oops, this is Docking Bay 95.',
	'What a piece of fast casual food!',
	'This isn\'t what we ordered!',
	'Let\'s get one thing straight. I take orders from just one person: me!',
	'But who\'s gonna fry it, kid? You?',
	'Mcdeck Officer!',
	'One things for sure, we\'re all gonna be a lot fatter.',
	'The Millennium Falcon, as designed by Claes Oldenburg',
	'She\'ll make .5 past bite speed. I\'ve made a number of \'special\' modifications to her...',
	'Luke & the gang immediately regretted toking hard on Tosche death sticks',
	'What a bite of chuck!',
	'Inside Han Solo\’s carbonite dreams...',
	'You know, maybe we should grab some lunch before we head off.',
	'Luke was regretting ordering the Han burger.',
	'It\’s coarse and it gets everywhere — oh, sorry, wrong cartoon.',
	'With a sinking feeling in his stomach, Luke realised that the fool who followed the fool was the more foolish.',
	'Yes, Luke, I\’m sure. He DEFINITELY said Docking Bay 95.',
	'It\'s a hamburger ship - Ric Olié',
	'Analyze, scrutinize, and would you like fries...',
	'94. 94 porgs for a patty of that size, surely. That was Luke\'s best guess, anyway - though he had a bad feeling that he might have overestimated. He really wanted to win that trip to Alderaan.',
	'I haven\'t smelt anything like that since the dark times, since I was last with you father.',
	'So Chewy... I\'m guessing this makes you his Han-burger helper?',
	'So, how\'d it taste? Meh. A little Chewy.',
	'Cut! Cut! I wanted twin suns for this scene, not twin buns!',
	'I want every caption we have to go under that cartoon. More! MORE! - Kylo Ren',
	'Damn it George! Stop it with these special editions!!',
	'She\’ll be fine as long as we don’t encounter any more space worms.”',
	'And did the hamburger eat Han?',
	'I just hope he was wearing his poo gloves.',
	'There\'s always a burger fish.',
	'The toothpick is what gives a burger it\’s power. It penetrates it and binds the whole thing together.',
	'She may not look like much, but she\'s got the olive where it counts, kid. I\'ve made a lot of special modifications myself.” - Han Solo',
	'Chewie \"This is the cargo we dropped at the sight of imperials. Jabba\'s lunch. He wants us dead now\"',
	'He won it off of Lando Carb-rissian.',
	'According to Onion Ring theory, this scene mirrors the RoTS scene of Obi Wan\'s arrival on Tatooine aboard a half empty milkshake.',
	'Ohhhh...Tony Consiglio’s roach story makes a lot more sense now.',
	'All right, men. Load your plates.',
	'What a piece of meat!',
	'The Hamburgler has the death sentence on 12 systems.',
	'#94, your order\'s ready.',
	'You came in that thing? You\’re braver than I thought!',
	'Great, Chewie - always thinking with your stomach.',
	'I\’ve outrun Imperial starships. Not the local bulk fruitcakes - I\’m talking about the big pizza slices.',
	'Sorry about the mess.',
	'It made the snack run in 12 parsecs.',
	'Originally it was a footlong sub but that was too similar to a sandwich from Space: 1999.',
	'Here we are...Docking Bay Heinz 57',
	'I don\'t want to be that guy...but I hate sesame seeds',
	'Munch it, Chewy',
	'Ah the famous Millennium Falafel I presume',
	'Not for the first time, Luke wondered if he had bitten off more than he could chew.',
	'You know what they call this is Amsterdam? The Royal with cheese!',
	'Luke, I\'m getting too old for this sort of thing.',
	'This is Worcestershire than Meg (my Worcestershire friend)',
	'Star Wars as watched by Mynocks.',
	'When the local hobby shop closed down.',
	'Years ago, you served my father the best burger he’s ever had in The Clone Wars theme restaurant...',
	'You came in that thing? You\'re braver than I thought',
	'You know what they call a hamburger on Tatooine? A Royal with cheese!',
	'That\’s no moon...',
	'What a piece of lunch!',
	'It made the colon run is less than 12 parsecs',
	'It\'s like a thousand captions suddenly cried out in excitement',
	'Open Sesame',
	'It made the Ketchup Run in less than twelve packets.',
	'What a scruffy looking nerf-burger!',
	'I hanker for the day of practical effects',
	'She may not look like much, but she\'s got it by the ounce, kid.',
	'The spice that Han was smuggling that day included: 2.5 tablespoons paprika, 2 tablespoons table salt, 2 tablespoons garlic powder, 1 tablespoon onion powder, 2 teaspoons black pepper, 2 teaspoons ground mustard, 1 teaspoon cayenne pepper.',
	'You’ve never heard of General HMW Dator and his Magical Wonderful Wheelie Machine? “Should I have?”',
	'You want to add a portion of TIEs with that?',
	'What a piece of junk food!',
	'I have a bad feeding about this',
	'Lando: What have you done to my chips?',
	'I\'ve seen things you people wouldn\'t believe. Attack ships on fire off the shoulder of Orion. I watched C-beams glitter in the dark near the Tannhäuser Gate. All those moments will be lost in time, like tears in rain. Time... to die. - R2-D2',
	'Damn it Special Edition Jabba! We leave you alone for two minutes!...',
	'Han, mah burger...',
	'You must be in a real pickle with the Empire. What did you do to cheese them off? Get aboard and we\'ll haul buns out of here.',
	'OOOHHHH. Docking Bay Ninety FOUR.',
	'Do you have a boyfriend? A nice boyfriend?',
	'Some of these unused Ralph Mcquarrie concepts were rejected for a reason.',
	'Oh no, looks like it\’s Cloud City with a chance of Spaceballs',
	'A bantha patty, the bun, 2 slices of moof cheese...and NO space onions. Let\'s just say we\'d like to avoid any Imperial condiments.',
	'Lucasfilm parted ways with SOLO\'s original directors Phil Lord and Chris Miller (21 JUMP STREET, CLOUDY WITH A CHANCE OF MEATBALLS), saying the duo\'s creative vision didn\'t line up with the company\'s interpretation of STAR WARS.',

]


	function newCaption() {
		var randomNumber = Math.floor(Math.random() * (captions.length));
		document.getElementById('captionDisplay').innerHTML = captions[randomNumber];
	}